"""

Django settings for optima project.



Generated by 'django-admin startproject' using Django 4.1.7.



For more information on this file, see

https://docs.djangoproject.com/en/4.1/topics/settings/



For the full list of settings and their values, see

https://docs.djangoproject.com/en/4.1/ref/settings/

"""



import os

from pathlib import Path



# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent





# Quick-start development settings - unsuitable for production

# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/



# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = 'django-insecure-40gl)s1=63_)n6(f&e9pf1w9yomxpg*-#c%&*wrjx%#@+34_ao'



# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True



#ALLOWED_HOSTS = ['.eco-fret.com','*.eco-fret.com','app.eco-fret.com','web.eco-fret.com','197.240.168.85','localhost','127.0.0.1','212.102.35.251','197.240.91.76','37.187.92.104','instafret.com','www.instafret.com','app.instafret.com','www.app.instafret.com']

 ALLOWED_HOSTS = [
    'app.instafret.com',
    'www.app.instafret.com',
    'instafret.com',
    '.instafret.com',  # Autorise tous les sous-domaines
     'web.eco-fret.com',
    '.eco-fret.com'  # Autorise tous les sous-domaines
]

# Application definition



INSTALLED_APPS = [

    'jazzmin',
    'optimasite.apps.OptimasiteConfig',

  #  'admin_interface',

 #   'colorfield',

    'django.contrib.admin',

    'django.contrib.auth',

    'django.contrib.contenttypes',

    'django.contrib.sessions',

    'django.contrib.messages',

    'django.contrib.staticfiles',

    'rest_framework',

    "corsheaders",

]



MIDDLEWARE = [

    "corsheaders.middleware.CorsMiddleware",

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    "django.middleware.common.CommonMiddleware",

]



ROOT_URLCONF = 'optima.urls'



TEMPLATES = [

    {

        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.debug',

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],

        },

    },

]



WSGI_APPLICATION = 'optima.wsgi.application'





# Database

# https://docs.djangoproject.com/en/4.1/ref/settings/#databases



DATABASES = {

    'default': {  

        'ENGINE': 'django.db.backends.mysql',  

        'NAME': 'ecofgphh_optimafret',  

        'USER': 'ecofgphh_ghofran',  

        'PASSWORD': 'r{d55u2Ow-=S',  

        'HOST': 'localhost',  

        'PORT': '3306',  

        'OPTIONS': {  

            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"  

        }  

    }  

}





# Password validation

# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators



AUTH_PASSWORD_VALIDATORS = [

    {

        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',

    },

]





# Internationalization

# https://docs.djangoproject.com/en/4.1/topics/i18n/



LANGUAGE_CODE = 'en-us'



TIME_ZONE = 'Africa/Algiers'



USE_I18N = True



USE_TZ = True





# Static files (CSS, JavaScript, Images)

# https://docs.djangoproject.com/en/4.1/howto/static-files/



#STATIC_URL = 'static/'
#STATIC_ROOT = os.path.join(BASE_DIR, 'static')

##STATIC_ROOT = '/home/ecofgphh/projet/optima/static/'

#MEDIA_ROOT = os.path.join(BASE_DIR, 'optimasite/uploads')

#MEDIA_URL = 'optimasite/uploads/'

#by maher 
# Configuration des fichiers statiques
STATIC_URL = '/static/'
STATIC_ROOT = '/home/ecofgphh/app.instafret.com/static'  # Pointe vers le domaine web

# Configuration des fichiers média
MEDIA_URL = '/uploads/'
MEDIA_ROOT = '/home/ecofgphh/home/optimasite/uploads'



# Default primary key field type

# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field



DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': [

        'rest_framework.authentication.BasicAuthentication',

        'rest_framework.authentication.SessionAuthentication',

    ],

    'DEFAULT_PERMISSION_CLASSES': [

        'rest_framework.permissions.AllowAny'

    ]

}

#CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOWED_ORIGINS = ["https://eco-fret.com","https://www.eco-fret.com","https://web.eco-fret.com","http://web.eco-fret.com","http://197.240.168.85","http://localhost:4200","http://212.102.35.251","http://197.240.91.76","http://www.instafret.com","http://www.instafret.com","https://www.instafret.com","https://www.instafret.com","http://instafret.com","https://instafret.com","https://app.instafret.com","http://app.instafret.com"]

#CORS_ALLOWED_ORIGIN_REGEXES = [r"^https:\/\/eco-fret.com:*([0-9]+)?$",]

# Configuration des logs pour le debug
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': '/home/ecofgphh/app.instafret.com/django_errors.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}



#Email Config
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST = 'mail.eco-fret.com'
#EMAIL_USE_TLS = False
#EMAIL_PORT = 465
#EMAIL_USE_SSL = True
#EMAIL_HOST_USER = 'marhba@eco-fret.com'
#EMAIL_HOST_PASSWORD = 'J5OtSw3QW{G1'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'instafret.com'
EMAIL_USE_TLS = False
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'hello@instafret.com'
EMAIL_HOST_PASSWORD = 'J5OtSw3QW{G1'