# Generated by Django 4.1.7 on 2023-05-23 10:29

from django.db import migrations, models
import django.db.models.deletion
import optimasite.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='C_invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.BooleanField(default=False)),
                ('stamp', models.IntegerField()),
                ('O_name', models.TextField()),
                ('O_address', models.TextField()),
                ('O_phone', models.TextField()),
                ('O_mat', models.TextField()),
                ('C_name', models.TextField()),
                ('C_address', models.TextField()),
                ('C_phone', models.TextField()),
                ('C_mat', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client invoice',
                'verbose_name_plural': 'Client invoices',
            },
        ),
        migrations.CreateModel(
            name='cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('mat', models.CharField(blank=True, max_length=255, null=True)),
                ('Gname', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('postalcode', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('VAT', models.IntegerField(blank=True, null=True)),
                ('logo', models.FileField(blank=True, max_length=255, null=True, upload_to=optimasite.models.companies.unique_file_path_logo)),
                ('banner', models.FileField(blank=True, max_length=255, null=True, upload_to=optimasite.models.companies.unique_file_path_banner)),
                ('patent', models.FileField(blank=True, max_length=255, null=True, upload_to=optimasite.models.companies.unique_file_path_patent)),
                ('RC', models.FileField(blank=True, max_length=255, null=True, upload_to=optimasite.models.companies.unique_file_path_RC)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='optimasite.cities')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='companyallservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'A company service',
                'verbose_name_plural': 'All company services',
            },
        ),
        migrations.CreateModel(
            name='companytypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Company type',
                'verbose_name_plural': 'Company types',
            },
        ),
        migrations.CreateModel(
            name='countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=3)),
                ('phone_code', models.CharField(max_length=5)),
                ('flag', models.CharField(max_length=5)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='currencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=3)),
                ('code', models.CharField(blank=True, max_length=1, null=True)),
                ('rate', models.FloatField()),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='genders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Gender',
                'verbose_name_plural': 'Genders',
            },
        ),
        migrations.CreateModel(
            name='languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=False)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='merchnature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Merch nature',
                'verbose_name_plural': 'Merch natures',
            },
        ),
        migrations.CreateModel(
            name='missions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('width', models.IntegerField()),
                ('length', models.IntegerField()),
                ('height', models.IntegerField()),
                ('ref', models.CharField(blank=True, max_length=255, null=True)),
                ('requester', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('PO', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('dep_address_start', models.DateTimeField()),
                ('dep_address_end', models.DateTimeField()),
                ('arr_address_start', models.DateTimeField()),
                ('arr_address_end', models.DateTimeField()),
                ('CRval', models.IntegerField()),
                ('insuranceval', models.IntegerField()),
                ('RPval', models.IntegerField()),
                ('CR_status', models.BooleanField()),
                ('RP_status', models.BooleanField()),
                ('CR', models.IntegerField(blank=True, null=True)),
                ('insurance', models.IntegerField(blank=True, null=True)),
                ('RP', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.IntegerField()),
                ('charge_S', models.DateTimeField(blank=True, null=True)),
                ('charge_E', models.DateTimeField(blank=True, null=True)),
                ('trip_S', models.DateTimeField(blank=True, null=True)),
                ('trip_E', models.DateTimeField(blank=True, null=True)),
                ('discharge_S', models.DateTimeField(blank=True, null=True)),
                ('discharge_E', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
            },
        ),
        migrations.CreateModel(
            name='missionsalloptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'A mission option',
                'verbose_name_plural': 'All mission options',
            },
        ),
        migrations.CreateModel(
            name='P_invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.BooleanField(default=False)),
                ('stamp', models.IntegerField()),
                ('O_name', models.TextField()),
                ('O_address', models.TextField()),
                ('O_phone', models.TextField()),
                ('O_mat', models.TextField()),
                ('C_name', models.TextField()),
                ('C_address', models.TextField()),
                ('C_phone', models.TextField()),
                ('C_mat', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Provider invoice',
                'verbose_name_plural': 'Provider invoices',
            },
        ),
        migrations.CreateModel(
            name='palettype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Palet type',
                'verbose_name_plural': 'Palet types',
            },
        ),
        migrations.CreateModel(
            name='paymenttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Payment type',
                'verbose_name_plural': 'Payment types',
            },
        ),
        migrations.CreateModel(
            name='permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rref', models.CharField(max_length=50)),
                ('count_type', models.IntegerField()),
                ('count', models.IntegerField(blank=True, null=True)),
                ('budget_type', models.IntegerField()),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('charge_date', models.DateField()),
                ('discharge_date', models.DateField()),
                ('state', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.TextField(blank=True, null=True)),
                ('VAT', models.IntegerField(blank=True, null=True)),
                ('C_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='optimasite.c_invoices')),
                ('P_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='optimasite.p_invoices')),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
            },
        ),
        migrations.CreateModel(
            name='settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('value', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to=optimasite.models.settings.unique_file_path_P)),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='statuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.FileField(blank=True, max_length=255, null=True, upload_to=optimasite.models.users.unique_file_path_P)),
                ('account_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_exp_permi', models.DateField(blank=True, null=True)),
                ('date_exp_inscri', models.DateField(blank=True, null=True)),
                ('CIN', models.CharField(blank=True, max_length=100, null=True)),
                ('image_permit', models.FileField(blank=True, max_length=255, null=True, upload_to=optimasite.models.users.unique_file_path_Per)),
                ('image_CIN', models.FileField(blank=True, max_length=255, null=True, upload_to=optimasite.models.users.unique_file_path_CIN)),
                ('patent', models.FileField(blank=True, max_length=255, null=True, upload_to=optimasite.models.users.unique_file_path_patent)),
                ('mat', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='optimasite.companies')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='optimasite.countries')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='optimasite.genders')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimasite.languages')),
                ('permissions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='optimasite.permissions')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='optimasite.statuses')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='usertypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'User type',
                'verbose_name_plural': 'User types',
            },
        ),
        migrations.CreateModel(
            name='VAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'VAT',
                'verbose_name_plural': 'VAT',
            },
        ),
        migrations.CreateModel(
            name='vehiclecategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('percentage', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
                ('upper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='optimasite.vehiclecategories')),
            ],
            options={
                'verbose_name': 'Vehicle category',
                'verbose_name_plural': 'Vehicle categories',
            },
        ),
        migrations.CreateModel(
            name='vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat', models.CharField(max_length=50)),
                ('mat2', models.CharField(blank=True, max_length=50, null=True)),
                ('mark', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('max_weight', models.IntegerField(blank=True, null=True)),
                ('terrestrial_height', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('km_t', models.IntegerField(blank=True, null=True)),
                ('max_speed', models.IntegerField(blank=True, null=True)),
                ('date_exp_assur', models.DateField(blank=True, null=True)),
                ('date_exp_inscri', models.DateField(blank=True, null=True)),
                ('vehicle_status', models.BooleanField(default=True)),
                ('image', models.FileField(blank=True, max_length=255, null=True, upload_to=optimasite.models.vehicles.unique_file_path_image)),
                ('image_CG', models.FileField(blank=True, max_length=255, null=True, upload_to=optimasite.models.vehicles.unique_file_path_CG)),
                ('image_CGP', models.FileField(blank=True, max_length=255, null=True, upload_to=optimasite.models.vehicles.unique_file_path_CGP)),
                ('image_insurance', models.FileField(blank=True, max_length=255, null=True, upload_to=optimasite.models.vehicles.unique_file_path_insurance)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimasite.vehiclecategories')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimasite.companies')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='vehiclesalloptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'A vehicle option',
                'verbose_name_plural': 'All vehicle options',
            },
        ),
        migrations.CreateModel(
            name='vehiclesoptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimasite.vehiclesalloptions')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_options', to='optimasite.vehicles')),
            ],
            options={
                'verbose_name': 'Vehicle option',
                'verbose_name_plural': 'Vehicle options',
            },
        ),
        migrations.CreateModel(
            name='usersaddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('Lat', models.CharField(max_length=25)),
                ('Lng', models.CharField(max_length=25)),
                ('active', models.IntegerField()),
                ('enterprise', models.CharField(max_length=255)),
                ('Rname', models.CharField(max_length=25)),
                ('tel', models.CharField(max_length=25)),
                ('tel1', models.CharField(blank=True, max_length=25, null=True)),
                ('tel2', models.CharField(blank=True, max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimasite.users')),
            ],
            options={
                'verbose_name': 'User addresse',
                'verbose_name_plural': 'User addresses',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='usertype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimasite.usertypes'),
        ),
        migrations.CreateModel(
            name='tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimasite.users')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
        migrations.CreateModel(
            name='requestsoptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimasite.vehiclesalloptions')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_options', to='optimasite.requests')),
            ],
            options={
                'verbose_name': 'Request option',
                'verbose_name_plural': 'Request options',
            },
        ),
        migrations.AddField(
            model_name='requests',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimasite.vehiclecategories'),
        ),
        migrations.AddField(
            model_name='requests',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='optimasite.companies'),
        ),
        migrations.AddField(
            model_name='requests',
            name='currency_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimasite.currencies'),
        ),
        migrations.AddField(
            model_name='requests',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimasite.paymenttype'),
        ),
        migrations.AddField(
            model_name='requests',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimasite.users'),
        ),
        migrations.CreateModel(
            name='requestoffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('active', models.IntegerField()),
                ('options', models.CharField(blank=True, max_length=255, null=True)),
                ('charge_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimasite.companies')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_offers', to='optimasite.requests')),
            ],
            options={
                'verbose_name': 'Request offer',
                'verbose_name_plural': 'Request offers',
            },
        ),
        migrations.AddField(
            model_name='p_invoices',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimasite.paymenttype'),
        ),
        migrations.CreateModel(
            name='missionsoptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_options', to='optimasite.missions')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimasite.missionsalloptions')),
            ],
            options={
                'verbose_name': 'Mission option',
                'verbose_name_plural': 'Mission options',
            },
        ),
        migrations.CreateModel(
            name='missions_tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lat', models.CharField(max_length=25)),
                ('Lng', models.CharField(max_length=25)),
                ('Accuracy', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_tracker', to='optimasite.missions')),
            ],
            options={
                'verbose_name': 'Missions tracker',
                'verbose_name_plural': 'Missions trackers',
            },
        ),
        migrations.AddField(
            model_name='missions',
            name='arr_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_arr_address', to='optimasite.usersaddresses'),
        ),
        migrations.AddField(
            model_name='missions',
            name='dep_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_dep_address', to='optimasite.usersaddresses'),
        ),
        migrations.AddField(
            model_name='missions',
            name='merch_nature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimasite.merchnature'),
        ),
        migrations.AddField(
            model_name='missions',
            name='palette_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimasite.palettype'),
        ),
        migrations.AddField(
            model_name='missions',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_missions', to='optimasite.requests'),
        ),
        migrations.CreateModel(
            name='mission_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=optimasite.models.mission_files.unique_file_path_P)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_files', to='optimasite.missions')),
            ],
            options={
                'verbose_name': 'Mission file',
                'verbose_name_plural': 'Mission files',
            },
        ),
        migrations.CreateModel(
            name='language_pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimasite.languages')),
            ],
            options={
                'verbose_name': 'Language pack',
                'verbose_name_plural': 'Language packs',
            },
        ),
        migrations.AddField(
            model_name='countries',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimasite.currencies'),
        ),
        migrations.CreateModel(
            name='companyservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimasite.companies')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimasite.companyallservices')),
            ],
            options={
                'verbose_name': 'Company service',
                'verbose_name_plural': 'Company services',
            },
        ),
        migrations.AddField(
            model_name='companies',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='optimasite.countries'),
        ),
        migrations.AddField(
            model_name='companies',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='optimasite.companytypes'),
        ),
        migrations.AddField(
            model_name='cities',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimasite.countries'),
        ),
        migrations.AddField(
            model_name='c_invoices',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimasite.paymenttype'),
        ),
        migrations.CreateModel(
            name='attributions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_rating', models.IntegerField(blank=True, null=True)),
                ('user_rating', models.IntegerField(blank=True, null=True)),
                ('vehicle_rating', models.IntegerField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='optimasite.companies')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribution', to='optimasite.missions')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribution', to='optimasite.requests')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribution', to='optimasite.users')),
                ('vehicle', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribution', to='optimasite.vehicles')),
            ],
            options={
                'verbose_name': 'Attribution',
                'verbose_name_plural': 'Attributions',
            },
        ),
    ]
