# Generated by Django 4.1.7 on 2023-06-16 14:04

from django.db import migrations, models
import django.db.models.deletion
import optimasite.models


class Migration(migrations.Migration):

    dependencies = [
        ('optimasite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='share_code',
            field=models.CharField(default='1234567', max_length=7),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='label',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='token',
            field=models.CharField(default=optimasite.models.tokens.unique_rand, max_length=32),
        ),
        migrations.CreateModel(
            name='requestcodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_codes', to='optimasite.requests')),
            ],
            options={
                'verbose_name': 'Request code',
                'verbose_name_plural': 'Request codes',
            },
        ),
    ]
