# Generated by Django 4.1.7 on 2023-06-26 12:21

from django.db import migrations, models
import django.db.models.deletion
import optimasite.models


class Migration(migrations.Migration):

    dependencies = [
        ('optimasite', '0002_companies_share_code_alter_currencies_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('pos', models.TextField(blank=True, null=True)),
                ('url', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('image', models.FileField(blank=True, max_length=255, null=True, upload_to=optimasite.models.banner.unique_file_path_patent)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.AddField(
            model_name='companyallservices',
            name='icon',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=optimasite.models.companyallservices.unique_file_path_patent),
        ),
        migrations.AddField(
            model_name='companytypes',
            name='icon',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=optimasite.models.companytypes.unique_file_path_patent),
        ),
        migrations.AddField(
            model_name='merchnature',
            name='icon',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=optimasite.models.merchnature.unique_file_path_patent),
        ),
        migrations.AddField(
            model_name='missionsalloptions',
            name='icon',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=optimasite.models.missionsalloptions.unique_file_path_patent),
        ),
        migrations.AddField(
            model_name='missionsalloptions',
            name='id_cat_parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='optimasite.vehiclecategories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='palettype',
            name='icon',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=optimasite.models.palettype.unique_file_path_patent),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='icon',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=optimasite.models.paymenttype.unique_file_path_patent),
        ),
        migrations.AddField(
            model_name='requests',
            name='backhaul_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='co2_coef_req',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='co2_consom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='co2_tax',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='qrcode_inv',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='qrcode_ok',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='qrcode_track',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='validation_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='bonus',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='referal_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='referee_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecategories',
            name='icon',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=optimasite.models.vehiclecategories.unique_file_path_patent),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='co2_coef_req',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclesalloptions',
            name='icon',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=optimasite.models.vehiclesalloptions.unique_file_path_patent),
        ),
        migrations.AlterField(
            model_name='companies',
            name='share_code',
            field=models.CharField(default=optimasite.models.companies.unique_rand, max_length=7),
        ),
    ]
