INSERT INTO `optimasite_settings` (`id`, `code`, `value`, `file`) VALUES
(NULL, 'invoice_company_name', 'Optimalogistic', NULL),
(NULL, 'invoice_company_mat', '1601996 G/A/M000', NULL),
(NULL, 'invoice_company_address', 'PEP. entreprise 3 technopole Sfax 3021. Tunisie', NULL),
(NULL, 'invoice_company_phone', '28132236', NULL),
(NULL, 'request_max_count', '20', NULL),
(NULL, 'invoice_stamp_tax_value', '1', NULL),
(NULL, 'header_logo', NULL, 'defaults/logos/H_logo.png'),
(NULL, 'logo', NULL, 'defaults/logos/logo.png'),
(NULL, 'invoice_logo', NULL, 'defaults/logos/I_logo.png');

INSERT INTO `optimasite_vat` (`id`, `value`, `active`) VALUES
(NULL, 0, 1),
(NULL, 7, 1),
(NULL, 12, 1),
(NULL, 19, 1);

INSERT INTO `optimasite_companyallservices` (`id`, `label`, `active`) VALUES
(NULL, 'lg_land_transport', 1),
(NULL, 'lg_logistic', 1),
(NULL, 'lg_international_transport', 1);

INSERT INTO `optimasite_companytypes` (`id`, `label`, `active`) VALUES
(1, 'lg_company', 1),
(2, 'lg_particular', 1);

INSERT INTO `optimasite_currencies` (`id`, `label`, `code`, `rate`, `active`) VALUES
(1, 'TND', NULL, 1, 1);

INSERT INTO `optimasite_countries` (`id`, `label`, `country_code`, `phone_code`, `flag`, `currency_id`, `active`) VALUES
(1, 'Tunisie', 'TN', '+216', 'tn', 1, 1);

INSERT INTO `optimasite_genders` (`id`, `label`, `active`) VALUES
(NULL, 'lg_male', 1),
(NULL, 'lg_female', 1);

INSERT INTO `optimasite_permissions` (`id`, `label`, `active`) VALUES
(1, 'lg_driver', 1),
(2, 'lg_manager', 1),
(3, 'lg_planner', 1),
(4, 'lg_park_manager', 1);

INSERT INTO `optimasite_usertypes` (`id`, `label`) VALUES
(1, 'lg_provider'),
(2, 'lg_client');

INSERT INTO `optimasite_cities` (`id`, `label`, `country_id`, `active`) VALUES
(NULL, 'Tunis', 1, 1),
(NULL, 'Ariana', 1, 1),
(NULL, 'Ben Arous', 1, 1),
(NULL, 'Manouba', 1, 1),
(NULL, 'Nabeul', 1, 1),
(NULL, 'Zaghouan', 1, 1),
(NULL, 'Bizerte', 1, 1),
(NULL, 'Béja', 1, 1),
(NULL, 'Jendouba', 1, 1),
(NULL, 'Kef', 1, 1),
(NULL, 'Siliana', 1, 1),
(NULL, 'Sousse', 1, 1),
(NULL, 'Monastir', 1, 1),
(NULL, 'Mahdia', 1, 1),
(NULL, 'Sfax', 1, 1),
(NULL, 'Kairouan', 1, 1),
(NULL, 'Kasserine', 1, 1),
(NULL, 'Sidi Bouzid', 1, 1),
(NULL, 'Gabès', 1, 1),
(NULL, 'Mednine', 1, 1),
(NULL, 'Tataouine', 1, 1),
(NULL, 'Gafsa', 1, 1),
(NULL, 'Tozeur', 1, 1),
(NULL, 'Kebili', 1, 1);

INSERT INTO `optimasite_statuses` (`id`, `label`, `active`) VALUES
(1, 'lg_active', 1),
(2, 'lg_inactive', 1),
(3, 'lg_on_leave', 1);

INSERT INTO `optimasite_vehiclecategories` (`id`, `label`, `upper_id`, `percentage`, `active`) VALUES
(NULL, 'lg_Import_Export', NULL, 1, 1),
(NULL, 'lg_land_transport', NULL, 1, 1),
(NULL, 'lg_flatbed_truck', 2, 1, 1),
(NULL, 'lg_cabin_truck', 2, 1, 1),
(NULL, 'lg_10T', 4, 10, 1),
(NULL, 'lg_storage', NULL, 1, 1);

INSERT INTO `optimasite_vehiclesalloptions` (`id`, `label`, `active`) VALUES
(NULL, 'lg_bache', 1),
(NULL, 'lg_tailgate', 1),
(NULL, 'lg_pallet_truck', 1),
(NULL, 'lg_side_panel', 1),
(NULL, 'lg_refrigeration_0', 1),
(NULL, 'lg_refrigeration_n6', 1),
(NULL, 'lg_refrigeration_n20', 1);

INSERT INTO `optimasite_palettype` (`id`, `label`, `length`, `width`, `active`) VALUES
(NULL, 'lg_EURO(120x80)', '120', '80', 1),
(NULL, 'lg_STD(100x120)', '100', '120', 1),
(NULL, 'lg_other_specify', NULL, NULL, 1);

INSERT INTO `optimasite_merchnature` (`id`, `label`, `active`) VALUES
(NULL, 'lg_metal', 1),
(NULL, 'lg_wood', 1),
(NULL, 'lg_food_products', 1),
(NULL, 'lg_plastic', 1),
(NULL, 'lg_construction_material', 1),
(NULL, 'lg_fresh_products', 1),
(NULL, 'lg_hazardous_products', 1),
(NULL, 'lg_hardware_products', 1),
(NULL, 'lg_appliances', 1),
(NULL, 'lg_fragile_lamp_glasses', 1),
(NULL, 'lg_variety', 1);

INSERT INTO `optimasite_paymenttype` (`id`, `label`, `active`) VALUES
(1, 'lg_wallet', 1),
(2, 'lg_cash_cod', 1),
(3, 'lg_check', 1),
(4, 'lg_bank_transfer', 1);

INSERT INTO `optimasite_missionsalloptions` (`id`, `label`, `active`) VALUES
(NULL, 'lg_covid_test', 1),
(NULL, 'lg_conveyor', 1),
(NULL, 'lg_unloading_bl', 1);

INSERT INTO `optimasite_languages` (`id`, `code`, `active`, `default`) VALUES
(1, 'eng', 1, 1),
(2, 'fr', 1, 0);

INSERT INTO `optimasite_language_pack` (`id`, `ref`, `value`, `code_id`) VALUES 
(NULL, 'lg_home', 'Home', '1'),
(NULL, 'lg_home', 'Accueil', '2'),
(NULL, 'lg_dashboard', 'Dashboard', '1'),
(NULL, 'lg_dashboard', 'Dashboard', '2'),
(NULL, 'lg_requests', 'Requests', '1'),
(NULL, 'lg_requests', 'Demandes', '2'),
(NULL, 'lg_signup', 'Create new account', '1'),
(NULL, 'lg_signup', 'Créer nouveau compte', '2'),
(NULL, 'lg_summary', 'Summary', '1'),
(NULL, 'lg_summary', 'Résumé', '2'),
(NULL, 'lg_company', 'Company', '1'),
(NULL, 'lg_company', 'Compagnie', '2'),
(NULL, 'lg_managers', 'Managers', '1'),
(NULL, 'lg_managers', 'Managers', '2'),
(NULL, 'lg_drivers', 'Drivers', '1'),
(NULL, 'lg_drivers', 'Chauffeurs', '2'),
(NULL, 'lg_vehicles', 'Vehicles', '1'),
(NULL, 'lg_vehicles', 'Véhicules', '2'),
(NULL, 'lg_attributions', 'Attributions', '1'),
(NULL, 'lg_attributions', 'Attributions', '2'),
(NULL, 'lg_driver_menu', 'Driver menu', '1'),
(NULL, 'lg_driver_menu', 'Menu chauffeur', '2'),
(NULL, 'lg_job', 'Job', '1'),
(NULL, 'lg_job', 'Travail', '2'),
(NULL, 'lg_history', 'History', '1'),
(NULL, 'lg_history', 'Historique', '2'),
(NULL, 'lg_my_profile', 'My profile', '1'),
(NULL, 'lg_my_profile', 'Mon profile', '2'),
(NULL, 'lg_logout', 'Logout', '1'),
(NULL, 'lg_logout', 'Déconnexion', '2'),
(NULL, 'lg_request', 'Request', '1'),
(NULL, 'lg_request', 'Demande', '2'),
(NULL, 'lg_welcome', 'Welcome', '1'),
(NULL, 'lg_welcome', 'Bienvenue', '2'),
(NULL, 'lg_options', 'Options', '1'),
(NULL, 'lg_options', 'Options', '2'),
(NULL, 'lg_select_request', 'Select a request', '1'),
(NULL, 'lg_select_request', 'Sélectionner une demande', '2'),
(NULL, 'lg_none', 'None', '1'),
(NULL, 'lg_none', 'Aucun', '2'),
(NULL, 'lg_task', 'Task', '1'),
(NULL, 'lg_task', 'Collecte', '2'),
(NULL, 'lg_select_task', 'Select a task', '1'),
(NULL, 'lg_select_task', 'Sélectionner une collecte', '2'),
(NULL, 'lg_all', 'All', '1'),
(NULL, 'lg_all', 'Tous', '2'),
(NULL, 'lg_vehicle', 'Vehilce', '1'),
(NULL, 'lg_vehicle', 'Véhicule', '2'),
(NULL, 'lg_select_vehicle', 'Select a vehicle', '1'),
(NULL, 'lg_select_vehicle', 'Sélectionner un véhicule', '2'),
(NULL, 'lg_driver', 'Driver', '1'),
(NULL, 'lg_driver', 'Chauffeur', '2'),
(NULL, 'lg_select_driver', 'Select a driver', '1'),
(NULL, 'lg_select_driver', 'Sélectionner un chauffeur', '2'),
(NULL, 'lg_add', 'Add', '1'),
(NULL, 'lg_add', 'Ajouter', '2'),
(NULL, 'lg_status', 'Status', '1'),
(NULL, 'lg_status', 'Statut', '2'),
(NULL, 'lg_action', 'Action', '1'),
(NULL, 'lg_action', 'Action', '2'),
(NULL, 'lg_not_attributed', 'Not attributed', '1'),
(NULL, 'lg_not_attributed', 'non attribuer', '2'),
(NULL, 'lg_all_tasks', 'All tasks', '1'),
(NULL, 'lg_all_tasks', 'Tous les Collectes', '2'),
(NULL, 'lg_awaiting_confirmation', 'Awaiting confirmation', '1'),
(NULL, 'lg_awaiting_confirmation', 'en attente de confirmation', '2'),
(NULL, 'lg_some_tasks_not_attributed_yet', 'Some tasks are not attributed yet', '1'),
(NULL, 'lg_some_tasks_not_attributed_yet', "certains collectes n'ont pas encore attribuer", '2'),
(NULL, 'lg_request_in_progress', 'Request in progress', '1'),
(NULL, 'lg_request_in_progress', 'Demande en cour', '2'),
(NULL, 'lg_request_completed', 'Request completed', '1'),
(NULL, 'lg_request_completed', 'Demande complète', '2'),
(NULL, 'lg_task_completed', 'Task completed', '1'),
(NULL, 'lg_task_completed', 'Collecte complète', '2'),
(NULL, 'lg_reuqest_completed_and_validated', 'Request completed and validated', '1'),
(NULL, 'lg_reuqest_completed_and_validated', 'Demande complètèe et validèe', '2'),
(NULL, 'lg_delete', 'Delete', '1'),
(NULL, 'lg_delete', 'Supprimer', '2'),
(NULL, 'lg_view', 'View', '1'),
(NULL, 'lg_view', 'Voir', '2'),
(NULL, 'lg_deletion', 'Deletion', '1'),
(NULL, 'lg_deletion', 'Suppression', '2'),
(NULL, 'lg_delete_this_attribution', 'Delete this attribution ?', '1'),
(NULL, 'lg_delete_this_attribution', 'Supprimer Cette attributions ?', '2'),
(NULL, 'lg_cancel', 'Cancel', '1'),
(NULL, 'lg_cancel', 'Annuler', '2'),
(NULL, 'lg_telephone', 'Telephone', '1'),
(NULL, 'lg_telephone', 'Téléphone', '2'),
(NULL, 'lg_plate', 'Plate', '1'),
(NULL, 'lg_plate', 'Matricule', '2'),
(NULL, 'lg_type_of_palletizing', 'Type of palletizing ', '1'),
(NULL, 'lg_type_of_palletizing', 'Type de palettage', '2'),
(NULL, 'lg_type_of_goods', 'Type of goods', '1'),
(NULL, 'lg_type_of_goods', 'Nature de marchandise', '2'),
(NULL, 'lg_number', 'Number', '1'),
(NULL, 'lg_number', 'Nombre', '2'),
(NULL, 'lg_weight', 'Weight', '1'),
(NULL, 'lg_weight', 'Poids', '2'),
(NULL, 'lg_width', 'Width', '1'),
(NULL, 'lg_width', 'Largeur', '2'),
(NULL, 'lg_length', 'Length', '1'),
(NULL, 'lg_length', 'Longueur', '2'),
(NULL, 'lg_height', 'Height', '1'),
(NULL, 'lg_height', 'Hauteur', '2'),
(NULL, 'lg_ref', 'Ref.', '1'),
(NULL, 'lg_ref', 'Réf.', '2'),
(NULL, 'lg_requestor', 'Requestor', '1'),
(NULL, 'lg_requestor', 'Requestor', '2'),
(NULL, 'lg_vendor', 'Vendor', '1'),
(NULL, 'lg_vendor', 'Vendor', '2'),
(NULL, 'lg_P/O', 'P/O', '1'),
(NULL, 'lg_P/O', 'P/O', '2'),
(NULL, 'lg_description', 'Description', '1'),
(NULL, 'lg_description', 'Description', '2'),
(NULL, 'lg_pickup_address', 'Pick up address', '1'),
(NULL, 'lg_pickup_address', 'Adresse de ramassage', '2'),
(NULL, 'lg_enterprise', 'Enterprise', '1'),
(NULL, 'lg_enterprise', 'Entreprise', '2'),
(NULL, 'lg_responsible_name', 'Responsible', '1'),
(NULL, 'lg_responsible_name', 'responsable', '2'),
(NULL, 'lg_from', 'From', '1'),
(NULL, 'lg_from', 'A partir de', '2'),
(NULL, 'lg_to', 'To', '1'),
(NULL, 'lg_to', "Jusqu'à", '2'),
(NULL, 'lg_dropoff_address', 'Drop off address', '1'),
(NULL, 'lg_dropoff_address', 'Adresse de dépôt', '2'),
(NULL, 'lg_cash_on_delivery', 'Cash on delivery', '1'),
(NULL, 'lg_cash_on_delivery', 'Contre remboursement', '2'),
(NULL, 'lg_check', 'Check', '1'),
(NULL, 'lg_check', 'Chéque', '2'),
(NULL, 'lg_cash', 'Cash', '1'),
(NULL, 'lg_cash', 'Espèce', '2'),
(NULL, 'lg_amount', 'Amount', '1'),
(NULL, 'lg_amount', 'Montant', '2'),
(NULL, 'lg_merchandise_insurance', 'Merchandise insurance', '1'),
(NULL, 'lg_merchandise_insurance', 'Assurance marchandise', '2'),
(NULL, 'lg_any_risk', 'Any risk', '1'),
(NULL, 'lg_any_risk', 'Tout risque', '2'),
(NULL, 'lg_merchandise_value', 'Merchandise value', '1'),
(NULL, 'lg_merchandise_value', 'Valeur de marchandise', '2'),
(NULL, 'lg_return_pallet', 'Return pallet', '1'),
(NULL, 'lg_return_pallet', 'Retour palette', '2'),
(NULL, 'lg_no', 'No', '1'),
(NULL, 'lg_no', 'Non', '2'),
(NULL, 'lg_yes', 'Yes', '1'),
(NULL, 'lg_yes', 'Oui', '2'),
(NULL, 'lg_general_options', 'General options', '1'),
(NULL, 'lg_general_options', 'Options générale', '2'),
(NULL, 'lg_tasks_list', 'Tasks list', '1'),
(NULL, 'lg_tasks_list', 'Liste de collectes', '2'),
(NULL, 'lg_experience_evaluation', 'Experience evaluation', '1'),
(NULL, 'lg_experience_evaluation', "évaluation de l'expérience", '2'),
(NULL, 'lg_website', 'Website', '1'),
(NULL, 'lg_website', 'Site web', '2'),
(NULL, 'lg_email', 'Email', '1'),
(NULL, 'lg_email', 'Email', '2'),
(NULL, 'lg_contact', 'Contact', '1'),
(NULL, 'lg_contact', 'Contact', '2'),
(NULL, 'lg_tasks_calendar', 'Tasks calendar', '1'),
(NULL, 'lg_tasks_calendar', 'Calendrier des Collectes', '2'),
(NULL, 'lg_begin_loading', 'Begin loading', '1'),
(NULL, 'lg_begin_loading', 'Debut chargement', '2'),
(NULL, 'lg_end_loading', 'End loading', '1'),
(NULL, 'lg_end_loading', 'Fin chargement', '2'),
(NULL, 'lg_begin_trip', 'Begin trip', '1'),
(NULL, 'lg_begin_trip', 'Debut déplacement', '2'),
(NULL, 'lg_end_trip', 'End trip', '1'),
(NULL, 'lg_end_trip', 'Fin déplacement', '2'),
(NULL, 'lg_begin_unloading', 'Begin unloading', '1'),
(NULL, 'lg_begin_unloading', 'Debut déchargement', '2'),
(NULL, 'lg_end_unloading', 'End unloading', '1'),
(NULL, 'lg_end_unloading', 'Fin déchargement', '2'),
(NULL, 'lg_propose_price', 'Propose a price', '1'),
(NULL, 'lg_propose_price', 'Proposer un prix', '2'),
(NULL, 'lg_loading_date', 'Loading date', '1'),
(NULL, 'lg_loading_date', 'Date de chargement', '2'),
(NULL, 'lg_unloading_date', 'Unloading date', '1'),
(NULL, 'lg_unloading_date', 'Date de déchargement', '2'),
(NULL, 'lg_propose', 'Propose', '1'),
(NULL, 'lg_propose', 'Proposer', '2'),
(NULL, 'lg_task_status', 'Task status', '1'),
(NULL, 'lg_task_status', 'Etat de collecte', '2'),
(NULL, 'lg_unloading_photos', 'Unloading photos', '1'),
(NULL, 'lg_unloading_photos', 'Photo de déchargement', '2'),
(NULL, 'lg_select', 'Select', '1'),
(NULL, 'lg_select', 'Selectioner', '2'),
(NULL, 'lg_select_photo', 'Select a photo', '1'),
(NULL, 'lg_select_photo', 'Selectioner une image', '2'),
(NULL, 'lg_ensure_uploaded_files_are_images', 'ensure that the uploaded files are images', '1'),
(NULL, 'lg_ensure_uploaded_files_are_images', 'assurer que les fichiers téléchargés sont des images', '2'),
(NULL, 'lg_ensure_uploaded_file_is_image', 'ensure that the uploaded file is an image', '1'),
(NULL, 'lg_ensure_uploaded_file_is_image', 'assurer que le fichier téléchargé est une image', '2'),
(NULL, 'lg_vehicle_count', 'Vehicle count', '1'),
(NULL, 'lg_vehicle_count', 'Nombre des véhicules', '2'),
(NULL, 'lg_vehicle_information', 'Vehicle information', '1'),
(NULL, 'lg_vehicle_information', 'Information de véhicule', '2'),
(NULL, 'lg_validate', 'Validate', '1'),
(NULL, 'lg_validate', 'Valider', '2'),
(NULL, 'lg_type', 'Type', '1'),
(NULL, 'lg_type', 'Type', '2'),
(NULL, 'lg_payment_type', 'Payment type', '1'),
(NULL, 'lg_payment_type', 'Type de paiement', '2'),
(NULL, 'lg_company_type', 'Company type', '1'),
(NULL, 'lg_company_type', 'Type de votre compagnie', '2'),
(NULL, 'lg_category', 'Category', '1'),
(NULL, 'lg_category', 'Catégorie', '2'),
(NULL, 'lg_select_category', 'Select a category', '1'),
(NULL, 'lg_select_category', 'Sélectionner une Catégorie', '2'),
(NULL, 'lg_subcategory', 'Subcategory', '1'),
(NULL, 'lg_subcategory', 'Sous-Catégorie', '2'),
(NULL, 'lg_insurance_exp_date', 'Insurance exp. date', '1'),
(NULL, 'lg_insurance_exp_date', 'Date exp. assurance', '2'),
(NULL, 'lg_quick_action', 'Quick action', '1'),
(NULL, 'lg_quick_action', 'Action rapide', '2'),
(NULL, 'lg_add_request', 'Add request', '1'),
(NULL, 'lg_add_request', 'Ajouter une commande', '2'),
(NULL, 'lg_add_task', 'Add task', '1'),
(NULL, 'lg_add_task', 'Ajouter une collecte', '2'),
(NULL, 'lg_attributed', 'Attributed', '1'),
(NULL, 'lg_attributed', 'attribué', '2'),
(NULL, 'lg_mark', 'Mark', '1'),
(NULL, 'lg_mark', 'Marque', '2'),
(NULL, 'lg_model', 'Model', '1'),
(NULL, 'lg_model', 'Modèle', '2'),
(NULL, 'lg_ground_height', 'Ground height', '1'),
(NULL, 'lg_ground_height', 'hauteur terrestre', '2'),
(NULL, 'lg_max_weight', 'Max weight', '1'),
(NULL, 'lg_max_weight', 'Poids max', '2'),
(NULL, 'lg_kilometre', 'kilometre', '1'),
(NULL, 'lg_kilometre', 'Kilométrage', '2'),
(NULL, 'lg_year', 'Year', '1'),
(NULL, 'lg_year', 'Année', '2'),
(NULL, 'lg_max_speed', 'Max speed', '1'),
(NULL, 'lg_max_speed', 'Vitesse max', '2'),
(NULL, 'lg_subscription_exp_date', 'Subscription exp. date', '1'),
(NULL, 'lg_subscription_exp_date', 'Date exp. inscription', '2'),
(NULL, 'lg_delivery_options', 'Delivery options', '1'),
(NULL, 'lg_delivery_options', 'Options de la livraison', '2'),
(NULL, 'lg_delete_vehicle_with_this_plate', 'Delete vehicle with this plate', '1'),
(NULL, 'lg_delete_vehicle_with_this_plate', 'Supprimer le vehicle avec cette matricule', '2'),
(NULL, 'lg_delete_this_profile', 'Delete this profile ?', '1'),
(NULL, 'lg_delete_this_profile', 'Supprimer ce profile ?', '2'),
(NULL, 'lg_delete_this_task', 'Delete this task ?', '1'),
(NULL, 'lg_delete_this_task', 'Supprimer cette collecte ?', '2'),
(NULL, 'lg_delete_this_request', 'Delete this request ?', '1'),
(NULL, 'lg_delete_this_request', 'Supprimer la demande ?', '2'),
(NULL, 'lg_delete_your_proposition', 'Delete your proposition', '1'),
(NULL, 'lg_delete_your_proposition', 'Supprimer votre proposition', '2'),
(NULL, 'lg_change_your_proposition', 'Change your proposition', '1'),
(NULL, 'lg_change_your_proposition', 'Changer votre proposition', '2'),
(NULL, 'lg_send_your_proposition', 'Send your proposition', '1'),
(NULL, 'lg_send_your_proposition', 'Envoyer votre proposition', '2'),
(NULL, 'lg_send_report_to_company', 'Send a report to the company', '1'),
(NULL, 'lg_send_report_to_company', 'Envoyer un rapport au compagnie', '2'),
(NULL, 'lg_deleted_on', 'Deleted on', '1'),
(NULL, 'lg_deleted_on', 'Supprimer le', '2'),
(NULL, 'lg_modify', 'Modify', '1'),
(NULL, 'lg_modify', 'Modifier', '2'),
(NULL, 'lg_attribute_driver_to_vehicle', 'Attribute a driver to this vehicle', '1'),
(NULL, 'lg_attribute_driver_to_vehicle', 'Attribuer un chauffeur au véhicule', '2'),
(NULL, 'lg_vehicle_photo', 'vehicle photo', '1'),
(NULL, 'lg_vehicle_photo', 'Photo de véhicule', '2'),
(NULL, 'lg_platform_registration_card', 'Platform registration card', '1'),
(NULL, 'lg_platform_registration_card', 'Carte grise plateau', '2'),
(NULL, 'lg_registration_card', 'Registration card', '1'),
(NULL, 'lg_registration_card', 'Carte grise', '2'),
(NULL, 'lg_insurance', 'Insurance', '1'),
(NULL, 'lg_insurance', 'Assurance', '2'),
(NULL, 'lg_save', 'Save', '1'),
(NULL, 'lg_save', 'Enregistrer', '2'),
(NULL, 'lg_save_and_add', 'Save and add', '1'),
(NULL, 'lg_save_and_add', 'Enregistrer et ajouter', '2'),
(NULL, 'lg_save_and_return', 'Save and return', '1'),
(NULL, 'lg_save_and_return', 'Enregistrer et retourner', '2'),
(NULL, 'lg_full_truck', 'Full truck', '1'),
(NULL, 'lg_full_truck', 'Camion complet', '2'),
(NULL, 'lg_pallet_group', 'Pallet group', '1'),
(NULL, 'lg_pallet_group', 'Groupage de palette', '2'),
(NULL, 'lg_print', 'Print', '1'),
(NULL, 'lg_print', 'Imprimer', '2'),
(NULL, 'lg_auction', 'Auction', '1'),
(NULL, 'lg_auction', 'Enchère', '2'),
(NULL, 'lg_fixed', 'Fixed', '1'),
(NULL, 'lg_fixed', 'Fixe', '2'),
(NULL, 'lg_your_proposition', 'Your proposition', '1'),
(NULL, 'lg_your_proposition', 'Votre proposition', '2'),
(NULL, 'lg_accepted_proposition', 'Accecpted proposition', '1'),
(NULL, 'lg_accepted_proposition', 'Proposition accepté', '2'),
(NULL, 'lg_loading', 'Loading', '1'),
(NULL, 'lg_loading', 'Chargement', '2'),
(NULL, 'lg_unloading', 'Unloading', '1'),
(NULL, 'lg_unloading', 'Déchargement', '2'),
(NULL, 'lg_offers', 'Offers', '1'),
(NULL, 'lg_offers', 'Offres', '2'),
(NULL, 'lg_shipping', 'Shipping', '1'),
(NULL, 'lg_shipping', 'Livraison', '2'),
(NULL, 'lg_password', 'Password', '1'),
(NULL, 'lg_password', 'Password', '2'),
(NULL, 'lg_remember_password', 'Remember password', '1'),
(NULL, 'lg_remember_password', 'Mémoriser le mot de passe', '2'),
(NULL, 'lg_forgot_password', 'Forgot password ?', '1'),
(NULL, 'lg_forgot_password', 'Mot de passe oublié ?', '2'),
(NULL, 'lg_new_on_optima', 'New on Optima', '1'),
(NULL, 'lg_new_on_optima', 'Nouveau sur Optima ?', '2'),
(NULL, 'lg_signin', 'Sign in', '1'),
(NULL, 'lg_signin', 'Se connecter', '2'),
(NULL, 'lg_click_here', 'Click here', '1'),
(NULL, 'lg_click_here', 'Cliquez ici', '2'),
(NULL, 'lg_username_or_telephone', 'Username', '1'),
(NULL, 'lg_username_or_telephone', "Nom d'utilisateur", '2'),
(NULL, 'lg_account_deactivated_contact_msg', 'your account is deactivated. please contact your company manager to reactivate your account', '1'),
(NULL, 'lg_account_deactivated_contact_msg', 'votre compte est désactivé. veuillez contacter un responsable de votre entreprise pour réactiver votre compte', '2'),
(NULL, 'lg_incorrect_info_msg', 'please ensure your username and password are correct', '1'),
(NULL, 'lg_incorrect_info_msg', "veuillez vous assurer que votre nom d'’'utilisateur et votre mot de passe sont exacts", '2'),
(NULL, 'lg_login_head_msg', "Don't miss your next opportunity. Log in to stay informed about your professional world.", '1'),
(NULL, 'lg_login_head_msg', 'Ne manquez pas votre prochaine occasion. Connectez-vous pour rester au courant de votre monde professionnel.', '2'),
(NULL, 'lg_join_optima', 'Join Optima', '1'),
(NULL, 'lg_join_optima', 'Rejoindre Optima', '2'),
(NULL, 'lg_enjoy_your_professional_life', 'Enjoy your professional life', '1'),
(NULL, 'lg_enjoy_your_professional_life', 'Profitez de votre vie professionnelle', '2'),
(NULL, 'lg_provider', 'Provider', '1'),
(NULL, 'lg_provider', 'Fournisseur', '2'),
(NULL, 'lg_client', 'Client', '1'),
(NULL, 'lg_client', 'Client', '2'),
(NULL, 'lg_username_taken', 'this username is taken', '1'),
(NULL, 'lg_username_taken', "ce nom d'utilisateur est pris", '2'),
(NULL, 'lg_username', 'Username', '1'),
(NULL, 'lg_username', "Nom d'utilisateur", '2'),
(NULL, 'lg_password', 'Password', '1'),
(NULL, 'lg_password', 'Mot de passe', '2'),
(NULL, 'lg_confirm_password', 'Confirm password', '1'),
(NULL, 'lg_confirm_password', 'Confirmer le mot de passe', '2'),
(NULL, 'lg_password_rule_msg', 'password must be more than 4 characters or numbers', '1'),
(NULL, 'lg_password_rule_msg', 'mot de passe doit être plus de 4 caractères ou numéros', '2'),
(NULL, 'lg_password_unidentical', 'non-identical password', '1'),
(NULL, 'lg_password_unidentical', 'mot de passe non identique', '2'),
(NULL, 'lg_select_type', 'Select a type', '1'),
(NULL, 'lg_select_type', 'Sélectionner un type', '2'),
(NULL, 'lg_already_on_optima', 'Already on Optima', '1'),
(NULL, 'lg_already_on_optima', 'Déjà sur Optima ?', '2'),
(NULL, 'lg_you_agree', 'You agree', '1'),
(NULL, 'lg_you_agree', 'Vous acceptez', '2'),
(NULL, 'lg_user_agreement_policy_msg', 'the user agreement, the privacy policy', '1'),
(NULL, 'lg_user_agreement_policy_msg', "le contrat d'utilisation, la politique de confidentialité", '2'),
(NULL, 'lg_cookie_policy_msg', 'the cookie policy', '1'),
(NULL, 'lg_cookie_policy_msg', 'la politique de cookies', '2'),
(NULL, 'lg_transport_requests', 'transport requests', '1'),
(NULL, 'lg_transport_requests', 'Demandes de transport', '2'),
(NULL, 'lg_company_information', 'Company information', '1'),
(NULL, 'lg_company_information', 'Information du compagnie', '2'),
(NULL, 'lg_company_name', 'Company name', '1'),
(NULL, 'lg_company_name', 'Nom du Société', '2'),
(NULL, 'lg_tax_registration', 'Tax registration', '1'),
(NULL, 'lg_tax_registration', 'Matricule fiscale', '2'),
(NULL, 'lg_manager_fullname', "Manager's full name", '1'),
(NULL, 'lg_manager_fullname', 'Nom complet du gérant', '2'),
(NULL, 'lg_country', 'Country', '1'),
(NULL, 'lg_country', 'Pays', '2'),
(NULL, 'lg_select_country', 'Select a country', '1'),
(NULL, 'lg_select_country', 'Sélectionner un pays', '2'),
(NULL, 'lg_city', 'City', '1'),
(NULL, 'lg_city', 'Ville', '2'),
(NULL, 'lg_select_city', 'Select a city', '1'),
(NULL, 'lg_select_city', 'Sélectionner une Ville', '2'),
(NULL, 'lg_postal_code', 'Postal code', '1'),
(NULL, 'lg_postal_code', 'Code postale', '2'),
(NULL, 'lg_email_address', 'Email address', '1'),
(NULL, 'lg_email_address', 'Adresse email', '2'),
(NULL, 'lg_address', 'Address', '1'),
(NULL, 'lg_address', 'Adresse', '2'),
(NULL, 'lg_logo', 'Logo', '1'),
(NULL, 'lg_logo', 'Logo', '2'),
(NULL, 'lg_banner', 'Banner', '1'),
(NULL, 'lg_banner', 'bannière', '2'),
(NULL, 'lg_patent', 'Patent', '1'),
(NULL, 'lg_patent', 'Patente', '2'),
(NULL, 'lg_CR_approval', 'CR or approval', '1'),
(NULL, 'lg_CR_approval', 'RC ou agréement', '2'),
(NULL, 'lg_services_offered', 'Services offered', '1'),
(NULL, 'lg_services_offered', 'Services offertes', '2'),
(NULL, 'lg_new_requests', 'New requests', '1'),
(NULL, 'lg_new_requests', 'Nouvelles demandes', '2'),
(NULL, 'lg_accepted_requests', 'Accepted requests', '1'),
(NULL, 'lg_accepted_requests', 'Demandes acceptées', '2'),
(NULL, 'lg_requests_in_progress', 'Requests in progress', '1'),
(NULL, 'lg_requests_in_progress', 'Demandes en cour', '2'),
(NULL, 'lg_non_verified_requests', 'Non verified requests', '1'),
(NULL, 'lg_non_verified_requests', 'Demandes non vérifiées', '2'),
(NULL, 'lg_completed_requests', 'Completed requests', '1'),
(NULL, 'lg_completed_requests', 'Demandes complètées', '2'),
(NULL, 'lg_no_job_attributed', 'No job attributed', '1'),
(NULL, 'lg_no_job_attributed', 'Pas de travail attribuer', '2'),
(NULL, 'lg_completed_requests_count', 'Completed requests count', '1'),
(NULL, 'lg_completed_requests_count', 'Nombres des demandes complètées', '2'),
(NULL, 'lg_job_attributed', 'Job attributed', '1'),
(NULL, 'lg_job_attributed', 'Travail attribuer', '2'),
(NULL, 'lg_total_tasks', 'Total tasks', '1'),
(NULL, 'lg_total_tasks', 'totale des collectes', '2'),
(NULL, 'lg_requests_graph', 'Requests graph', '1'),
(NULL, 'lg_requests_graph', 'Graphe des demandes', '2'),
(NULL, 'lg_weekly', 'Weekly', '1'),
(NULL, 'lg_weekly', 'Semaine', '2'),
(NULL, 'lg_monthly', 'Monthly', '1'),
(NULL, 'lg_monthly', 'Mensuel', '2'),
(NULL, 'lg_yearly', 'Yearly', '1'),
(NULL, 'lg_yearly', 'Annuel', '2'),
(NULL, 'lg_employees_analytics', 'Employees analytics', '1'),
(NULL, 'lg_employees_analytics', 'Analytiques des employés', '2'),
(NULL, 'lg_park_manager', 'Park manager', '1'),
(NULL, 'lg_park_manager', 'Chef de parc', '2'),
(NULL, 'lg_planner', 'planner', '1'),
(NULL, 'lg_planner', 'Planificateur', '2'),
(NULL, 'lg_manager', 'Manager', '1'),
(NULL, 'lg_manager', 'Manager', '2'),
(NULL, 'lg_requests_analytics', 'Requests analytics', '1'),
(NULL, 'lg_requests_analytics', 'Analytiques des demandes', '2'),
(NULL, 'lg_new', 'New', '1'),
(NULL, 'lg_new', 'Nouvelles', '2'),
(NULL, 'lg_accepted', 'Accepted', '1'),
(NULL, 'lg_accepted', 'Acceptées', '2'),
(NULL, 'lg_in_progress', 'In progress', '1'),
(NULL, 'lg_in_progress', 'En cours', '2'),
(NULL, 'lg_non_verified', 'Non verified', '1'),
(NULL, 'lg_non_verified', 'Non vérifiées', '2'),
(NULL, 'lg_home_title_1', 'Logistics optimization', '1'),
(NULL, 'lg_home_title_1', 'Optimisation logistiques', '2'),
(NULL, 'lg_home_title_2', 'transport goods', '1'),
(NULL, 'lg_home_title_2', 'Transport marchandises', '2'),
(NULL, 'lg_home_sub_title', 'fast, efficient and economical', '1'),
(NULL, 'lg_home_sub_title', 'Rapide, efficace et économique', '2'),
(NULL, 'lg_land_transport', 'land transport', '1'),
(NULL, 'lg_land_transport', 'Transport terrestre', '2'),
(NULL, 'lg_search', 'Search', '1'),
(NULL, 'lg_search', 'Rechercher', '2'),
(NULL, 'lg_trusted_by_msg', 'Trusted by over 2M+ users', '1'),
(NULL, 'lg_trusted_by_msg', "2M+ d'utilisateurs font confiance", '2'),
(NULL, 'lg_transport_vehicles', 'Transport vehicles', '1'),
(NULL, 'lg_transport_vehicles', 'Véhicules de transport', '2'),
(NULL, 'lg_requests_delivered', 'Requests delivered ', '1'),
(NULL, 'lg_requests_delivered', 'Demandes livrées', '2'),
(NULL, 'lg_client_block_1', 'I want to send or store', '1'),
(NULL, 'lg_client_block_1', 'Je veux envoyer ou stocker', '2'),
(NULL, 'lg_client_block_2', 'goods', '1'),
(NULL, 'lg_client_block_2', 'des marchandises', '2'),
(NULL, 'lg_client_block_3', 'Find the best logistics provider for your needs from our trusted community.', '1'),
(NULL, 'lg_client_block_3', 'Trouver le meilleur fournisseur logistique pour vos besoins depuis notre communauté de confiance.', '2'),
(NULL, 'lg_provider_block_1', 'logistics', '1'),
(NULL, 'lg_provider_block_1', 'Transporteur ou fournisseur', '2'),
(NULL, 'lg_provider_block_2', 'Provider or supplier', '1'),
(NULL, 'lg_provider_block_2', 'logistique', '2'),
(NULL, 'lg_provider_block_3', 'Publish your services and start exploring new opportunities and build your brand.', '1'),
(NULL, 'lg_provider_block_3', 'Publier vos services et commencez à explorer des nouvelles opportinutés et bâtir votre image de marque.', '2'),
(NULL, 'lg_last_vehicles_online', 'Last vehicles online', '1'),
(NULL, 'lg_last_vehicles_online', 'Derniers camions en ligne', '2'),
(NULL, 'lg_home_vehicle_block', 'Choose your supplier with the best value for money', '1'),
(NULL, 'lg_home_vehicle_block', 'Choisissez votre fournisseur avec le meilleur rapport qualité prix', '2'),
(NULL, 'lg_home_last_requests_block_1', 'Latest', '1'),
(NULL, 'lg_home_last_requests_block_1', 'Les dernières', '2'),
(NULL, 'lg_home_last_requests_block_2', 'Published requests', '1'),
(NULL, 'lg_home_last_requests_block_2', 'missions publiées', '2'),
(NULL, 'lg_home_last_requests_block_3', 'Contractual or auction requests', '1'),
(NULL, 'lg_home_last_requests_block_3', 'Des missions contractuels ou aux enchères', '2'),
(NULL, 'lg_request_deleted', 'Request deleted', '1'),
(NULL, 'lg_request_deleted', 'Demande supprimer', '2'),
(NULL, 'lg_request_created_successfully', 'Request created successfully', '1'),
(NULL, 'lg_request_created_successfully', 'Demande affectuer avec succès', '2'),
(NULL, 'lg_request_succ_created_msg', 'Request created and added to your request list', '1'),
(NULL, 'lg_request_succ_created_msg', 'Demande affectuer et ajouter a votre liste de demandes', '2'),
(NULL, 'lg_driver_information', 'Driver information', '1'),
(NULL, 'lg_driver_information', 'Information de chauffeur', '2'),
(NULL, 'lg_gender', 'Gender', '1'),
(NULL, 'lg_gender', 'Genre', '2'),
(NULL, 'lg_lastname', 'Last name', '1'),
(NULL, 'lg_lastname', 'Nom', '2'),
(NULL, 'lg_fullname', 'Full name', '1'),
(NULL, 'lg_fullname', 'Nom et Prenom', '2'),
(NULL, 'lg_firstname', 'First name', '1'),
(NULL, 'lg_firstname', 'Prénom', '2'),
(NULL, 'lg_birthdate', 'Birthdate', '1'),
(NULL, 'lg_birthdate', 'Date de naissance', '2'),
(NULL, 'lg_cin', 'CIN', '1'),
(NULL, 'lg_cin', 'CIN', '2'),
(NULL, 'lg_language', 'Language', '1'),
(NULL, 'lg_language', 'Langage', '2'),
(NULL, 'lg_profile_photo', 'Profile photo', '1'),
(NULL, 'lg_profile_photo', 'Photo de profil', '2'),
(NULL, 'lg_driver_licence', 'Driver licence', '1'),
(NULL, 'lg_driver_licence', 'Permis de conduire', '2'),
(NULL, 'lg_identity_card', 'Identity card', '1'),
(NULL, 'lg_identity_card', "Carte d'identite", '2'),
(NULL, 'lg_licence_exp_date', 'Licence exp. date', '1'),
(NULL, 'lg_licence_exp_date', 'Date exp. permis', '2'),
(NULL, 'lg_confirm', 'Confirm', '1'),
(NULL, 'lg_confirm', 'Confimer', '2'),
(NULL, 'lg_select_gender', 'Select a gender', '1'),
(NULL, 'lg_select_gender', 'Sélectionner un genre', '2'),
(NULL, 'lg_attribute_vehicle_to_driver', 'Attribute a vehicle to this driver', '1'),
(NULL, 'lg_attribute_vehicle_to_driver', 'Attribuer un véhicule au chauffeur', '2'),
(NULL, 'lg_select_status', 'Select a status', '1'),
(NULL, 'lg_select_status', 'Sélectionner un statut', '2'),
(NULL, 'lg_subscription_date', 'Subscription date', '1'),
(NULL, 'lg_subscription_date', "Date d'inscription", '2'),
(NULL, 'lg_individual_information', "individual's information", '1'),
(NULL, 'lg_individual_information', "Information de l'individuel", '2'),
(NULL, 'lg_permissions_group', 'Permissions group', '1'),
(NULL, 'lg_permissions_group', 'Groupe de permissions', '2'),
(NULL, 'lg_select_permissions', 'Select permissions', '1'),
(NULL, 'lg_select_permissions', 'Sélectionner une permission', '2'),
(NULL, 'lg_permissions', 'Permissions', '1'),
(NULL, 'lg_permissions', 'Permissions', '2'),
(NULL, 'lg_user_information', 'User information', '1'),
(NULL, 'lg_user_information', "Information d'utilisateur", '2'),
(NULL, 'lg_delivery_details', 'Delivery details', '1'),
(NULL, 'lg_delivery_details', 'Détails de la livraison', '2'),
(NULL, 'lg_goods_details', 'Goods details', '1'),
(NULL, 'lg_goods_details', 'Détails des Marchandises', '2'),
(NULL, 'lg_validation_progress', 'Validation progress', '1'),
(NULL, 'lg_validation_progress', 'Taux de validation', '2'),
(NULL, 'lg_request_quick_action_1_1', 'Duplicate a delivery (leave blank if none)', '1'),
(NULL, 'lg_request_quick_action_1_1', 'Dupliquer une livraison (laisser vide si aucun)', '2'),
(NULL, 'lg_request_quick_action_1_2', 'Type your reference to re-use an old request', '1'),
(NULL, 'lg_request_quick_action_1_2', 'Taper votre référence pour ré-utiliser une ancienne demande', '2'),
(NULL, 'lg_request_quick_action_2_1', 'Choose a provider (leave blank if none)', '1'),
(NULL, 'lg_request_quick_action_2_1', 'Choisir un transporteur (laisser vide si aucun)', '2'),
(NULL, 'lg_request_quick_action_2_2', 'Type the provider reference to send the request', '1'),
(NULL, 'lg_request_quick_action_2_2', 'Taper le référence transporteur pour lui envoyer la demande', '2'),
(NULL, 'lg_next', 'Next', '1'),
(NULL, 'lg_next', 'Suivant', '2'),
(NULL, 'lg_enter_internal_ref', 'Enter your internal reference', '1'),
(NULL, 'lg_enter_internal_ref', 'Entrer votre référence interne', '2'),
(NULL, 'lg_budget_number_deliveries', 'Budget and number of deliveries', '1'),
(NULL, 'lg_budget_number_deliveries', 'Budget et nombre de livraison', '2'),
(NULL, 'lg_specify_truck_groupage', 'Specify if the truck in groupage with the number', '1'),
(NULL, 'lg_specify_truck_groupage', 'Spécifier si le camion en groupage avec le nombre', '2'),
(NULL, 'lg_auction_fixed_price', 'Your budget: Auction or fixed price ', '1'),
(NULL, 'lg_auction_fixed_price', 'Votre budget: Prix au enchère ou fixe ', '2'),
(NULL, 'lg_schedule', 'Schedule', '1'),
(NULL, 'lg_schedule', 'Horaire', '2'),
(NULL, 'lg_today', 'Today', '1'),
(NULL, 'lg_today', "Aujourd'hui", '2'),
(NULL, 'lg_tomorrow', 'Tomorrow', '1'),
(NULL, 'lg_tomorrow', 'Demain', '2'),
(NULL, 'lg_vehicle_options', 'Vehicle options', '1'),
(NULL, 'lg_vehicle_options', 'Les options du véhicule', '2'),
(NULL, 'lg_Select_one_or_more_options', 'Select one or more options', '1'),
(NULL, 'lg_Select_one_or_more_options', 'Sélectionner un ou plusieurs options', '2'),
(NULL, 'lg_return', 'Return', '1'),
(NULL, 'lg_return', 'Retour', '2'),
(NULL, 'lg_collection_of_goods', 'Collection of goods', '1'),
(NULL, 'lg_collection_of_goods', 'Collecte de marchandises', '2'),
(NULL, 'lg_address_list', 'Address list', '1'),
(NULL, 'lg_address_list', 'liste des adresses', '2'),
(NULL, 'lg_nature', 'Nature', '1'),
(NULL, 'lg_nature', 'Nature', '2'),
(NULL, 'lg_pickup', 'Pick up', '1'),
(NULL, 'lg_pickup', 'Ramassage', '2'),
(NULL, 'lg_dropoff', 'Drop off', '1'),
(NULL, 'lg_dropoff', 'Dépôt', '2'),
(NULL, 'lg_view_details', 'View details', '1'),
(NULL, 'lg_view_details', 'Voir Details', '2'),
(NULL, 'lg_view_propositions', 'View propositions', '1'),
(NULL, 'lg_view_propositions', 'Voir Propositions', '2'),
(NULL, 'lg_informations', 'Informations', '1'),
(NULL, 'lg_informations', 'Informations', '2'),
(NULL, 'lg_select_address', 'Select an address', '1'),
(NULL, 'lg_select_address', 'Sélectionner une adresse', '2'),
(NULL, 'lg_pickup_schedule', 'Pick up schedule', '1'),
(NULL, 'lg_pickup_schedule', 'Horaire de ramassage', '2'),
(NULL, 'lg_dropoff_schedule', 'Drop off schedule', '1'),
(NULL, 'lg_dropoff_schedule', 'Horaire de dépôt', '2'),
(NULL, 'lg_add_address', 'Add an address', '1'),
(NULL, 'lg_add_address', 'Ajouter une adresse', '2'),
(NULL, 'lg_validate_request', 'Validate request', '1'),
(NULL, 'lg_validate_request', 'Valider la demande', '2'),
(NULL, 'lg_report', 'Report', '1'),
(NULL, 'lg_report', 'Rapport', '2'),
(NULL, 'lg_last_interaction', 'Last interaction', '1'),
(NULL, 'lg_last_interaction', 'Dernière interaction', '2'),
(NULL, 'lg_propositions', 'Propositions', '1'),
(NULL, 'lg_propositions', 'Propositions', '2'),
(NULL, 'lg_proposition', 'Proposition', '1'),
(NULL, 'lg_proposition', 'Proposition', '2'),
(NULL, 'lg_init_request', 'Initiate the request', '1'),
(NULL, 'lg_init_request', 'Lancer la demande', '2'),
(NULL, 'lg_init_request_q', 'Initiate the request ?', '1'),
(NULL, 'lg_init_request_q', 'Lancer la demande ?', '2'),
(NULL, 'lg_attention', 'Attention', '1'),
(NULL, 'lg_attention', 'Attention', '2'),
(NULL, 'lg_request_init_warn_msg', 'Perform necessary attributions before initiating the request', '1'),
(NULL, 'lg_request_init_warn_msg', 'Effectuer les attributions nécessaires avant de lancer la demande', '2'),
(NULL, 'lg_attribute', 'Attribute', '1'),
(NULL, 'lg_attribute', 'Attribuer', '2'),
(NULL, 'lg_confirmation', 'Confirmation', '1'),
(NULL, 'lg_confirmation', 'Confirmation', '2'),
(NULL, 'lg_initiate', 'Initiate', '1'),
(NULL, 'lg_initiate', 'Lancer', '2'),
(NULL, 'lg_request_validation', 'Request validation', '1'),
(NULL, 'lg_request_validation', 'Validation de la demande', '2'),
(NULL, 'lg_evaluate_experience_with', 'Evaluate your experience with', '1'),
(NULL, 'lg_evaluate_experience_with', 'évaluez votre expérience avec', '2'),
(NULL, 'lg_conclusion', 'Conclusion', '1'),
(NULL, 'lg_conclusion', 'Conclusion', '2'),
(NULL, 'lg_optional', 'Optional', '1'),
(NULL, 'lg_optional', 'Optionnel', '2'),
(NULL, 'lg_send', 'Send', '1'),
(NULL, 'lg_send', 'Envoyer', '2'),
(NULL, 'lg_unloading_docs', 'Unloading documents', '1'),
(NULL, 'lg_unloading_docs', 'Documents de déchargement', '2'),
(NULL, 'lg_completed', 'Completed', '1'),
(NULL, 'lg_completed', 'Complètées', '2'),
(NULL, 'lg_rejected', 'Rejected', '1'),
(NULL, 'lg_rejected', 'Rejetées', '2'),
(NULL, 'lg_search', 'Search', '1'),
(NULL, 'lg_search', 'Recherche', '2'),
(NULL, 'lg_empty', 'Empty', '1'),
(NULL, 'lg_empty', 'Vide', '2'),
(NULL, 'lg_monday', 'Monday', '1'),
(NULL, 'lg_monday', 'Lundi', '2'),
(NULL, 'lg_tuesday', 'Tuesday', '1'),
(NULL, 'lg_tuesday', 'Mardi', '2'),
(NULL, 'lg_wednesday', 'Wednesday', '1'),
(NULL, 'lg_wednesday', 'Mercredi', '2'),
(NULL, 'lg_thursday', 'Thursday', '1'),
(NULL, 'lg_thursday', 'Jeudi', '2'),
(NULL, 'lg_friday', 'Friday', '1'),
(NULL, 'lg_friday', 'Vendredi', '2'),
(NULL, 'lg_saturday', 'Saturday', '1'),
(NULL, 'lg_saturday', 'Samedi', '2'),
(NULL, 'lg_sunday', 'Sunday', '1'),
(NULL, 'lg_sunday', 'Dimanche', '2'),
(NULL, 'lg_total', 'Total', '1'),
(NULL, 'lg_total', 'Total', '2'),
(NULL, 'lg_january', 'January', '1'),
(NULL, 'lg_january', 'Janvier', '2'),
(NULL, 'lg_february', 'February', '1'),
(NULL, 'lg_february', 'Février', '2'),
(NULL, 'lg_march', 'March', '1'),
(NULL, 'lg_march', 'Mars', '2'),
(NULL, 'lg_april', 'April', '1'),
(NULL, 'lg_april', 'Avril', '2'),
(NULL, 'lg_may', 'May', '1'),
(NULL, 'lg_may', 'Mai', '2'),
(NULL, 'lg_june', 'June', '1'),
(NULL, 'lg_june', 'Juin', '2'),
(NULL, 'lg_july', 'July', '1'),
(NULL, 'lg_july', 'Juillet', '2'),
(NULL, 'lg_august', 'August', '1'),
(NULL, 'lg_august', 'Aout', '2'),
(NULL, 'lg_september', 'September', '1'),
(NULL, 'lg_september', 'Septembre', '2'),
(NULL, 'lg_october', 'October', '1'),
(NULL, 'lg_october', 'Octobre', '2'),
(NULL, 'lg_november', 'November', '1'),
(NULL, 'lg_november', 'Novembre', '2'),
(NULL, 'lg_december', 'December', '1'),
(NULL, 'lg_december', 'Décembre', '2'),
(NULL, 'lg_gps_err_msg', 'please ensure your GPS is enabled and give access to this application', '1'),
(NULL, 'lg_gps_err_msg', 'veuillez vous assurer que votre GPS est activé et donner accès à cette application', '2'),
(NULL, 'lg_activate_tracker', 'Activate stracker', '1'),
(NULL, 'lg_activate_tracker', 'Activer suivi', '2'),
(NULL, 'lg_deactivate_tracker', 'Deactivate stracker', '1'),
(NULL, 'lg_deactivate_tracker', 'Désactiver suivi', '2'),
(NULL, 'lg_last_tracker_update', 'Last tracker update on', '1'),
(NULL, 'lg_last_tracker_update', 'Dernière mise à jour de suivi le', '2'),
(NULL, 'lg_end_of_data', 'End of data', '1'),
(NULL, 'lg_end_of_data', 'fin des données', '2'),
(NULL, 'lg_first', 'First', '1'),
(NULL, 'lg_first', 'Debut', '2'),
(NULL, 'lg_last', 'Last', '1'),
(NULL, 'lg_last', 'Fin', '2'),
(NULL, 'lg_Import_Export', 'Import/Export', '1'),
(NULL, 'lg_Import_Export', 'Import/Export', '2'),
(NULL, 'lg_flatbed_truck', 'Flatbed truck', '1'),
(NULL, 'lg_flatbed_truck', 'Camion plateau', '2'),
(NULL, 'lg_cabin_truck', 'Cabin truck', '1'),
(NULL, 'lg_cabin_truck', 'Camion cabine', '2'),
(NULL, 'lg_10T', '10T', '1'),
(NULL, 'lg_10T', '10T', '2'),
(NULL, 'lg_storage', 'Storage', '1'),
(NULL, 'lg_storage', 'Stockage', '2'),
(NULL, 'lg_wallet', 'Wallet', '1'),
(NULL, 'lg_wallet', 'Wallet', '2'),
(NULL, 'lg_cash_cod', 'Cash(COD)', '1'),
(NULL, 'lg_cash_cod', 'Cash(COD)', '2'),
(NULL, 'lg_bank_transfer', 'Bank transfer', '1'),
(NULL, 'lg_bank_transfer', 'Virement bancaire', '2'),
(NULL, 'lg_logistic', 'Logistic', '1'),
(NULL, 'lg_logistic', 'Logistique', '2'),
(NULL, 'lg_international_transport', 'International transport', '1'),
(NULL, 'lg_international_transport', 'Transport international', '2'),
(NULL, 'lg_company', 'Company', '1'),
(NULL, 'lg_company', 'Société', '2'),
(NULL, 'lg_particular', 'Particular', '1'),
(NULL, 'lg_particular', 'Particulier', '2'),
(NULL, 'lg_provider', 'Provider', '1'),
(NULL, 'lg_provider', 'Fournisseur', '2'),
(NULL, 'lg_male', 'Male', '1'),
(NULL, 'lg_male', 'Masculin', '2'),
(NULL, 'lg_female', 'Female', '1'),
(NULL, 'lg_female', 'Feminin', '2'),
(NULL, 'lg_active', 'Active', '1'),
(NULL, 'lg_active', 'Active', '2'),
(NULL, 'lg_inactive', 'Inactive', '1'),
(NULL, 'lg_inactive', 'Inactive', '2'),
(NULL, 'lg_on_leave', 'On leave', '1'),
(NULL, 'lg_on_leave', 'Congé', '2'),
(NULL, 'lg_bache', 'Bache', '1'),
(NULL, 'lg_bache', 'Bache', '2'),
(NULL, 'lg_tailgate', 'Tailgate', '1'),
(NULL, 'lg_tailgate', 'Hayon', '2'),
(NULL, 'lg_pallet_truck', 'Pallet truck', '1'),
(NULL, 'lg_pallet_truck', 'Transpalette', '2'),
(NULL, 'lg_side_panel', 'Side panel', '1'),
(NULL, 'lg_side_panel', 'Ridelle', '2'),
(NULL, 'lg_refrigeration_0', 'Refrigeration 0++', '1'),
(NULL, 'lg_refrigeration_0', 'Frigorifique 0++', '2'),
(NULL, 'lg_refrigeration_n6', 'Refrigeration -6C -> 0++', '1'),
(NULL, 'lg_refrigeration_n6', 'Frigorifique -6C -> 0++', '2'),
(NULL, 'lg_refrigeration_n20', 'Refrigeration -20C -> -15C', '1'),
(NULL, 'lg_refrigeration_n20', 'Frigorifique -20C -> -15C', '2'),
(NULL, 'lg_EURO(120x80)', 'EURO (120x80)', '1'),
(NULL, 'lg_EURO(120x80)', 'EURO (120x80)', '2'),
(NULL, 'lg_STD(100x120)', 'STD (100x120)', '1'),
(NULL, 'lg_STD(100x120)', 'STD (100x120)', '2'),
(NULL, 'lg_other_specify', 'Other (specify)', '1'),
(NULL, 'lg_other_specify', 'Autre (A spécifier)', '2'),
(NULL, 'lg_select_nature', 'Select a nature', '1'),
(NULL, 'lg_select_nature', 'Sélectionner un nature', '2'),
(NULL, 'lg_covid_test', 'COVID TEST', '1'),
(NULL, 'lg_covid_test', 'TEST COVID', '2'),
(NULL, 'lg_conveyor', 'CONVEYOR', '1'),
(NULL, 'lg_conveyor', 'CONVOYEUR', '2'),
(NULL, 'lg_unloading_bl', 'UNLOADING BL', '1'),
(NULL, 'lg_unloading_bl', 'DECHARGE BL', '2'),
(NULL, 'lg_metal', 'METAL', '1'),
(NULL, 'lg_metal', 'METAL', '2'),
(NULL, 'lg_wood', 'WOOD', '1'),
(NULL, 'lg_wood', 'BOIS', '2'),
(NULL, 'lg_food_products', 'FOOD PRODUCTS', '1'),
(NULL, 'lg_food_products', 'PRODUITS ALIMENTAIRES', '2'),
(NULL, 'lg_plastic', 'PLASTIC', '1'),
(NULL, 'lg_plastic', 'PLASTIQUE', '2'),
(NULL, 'lg_construction_material', 'CONSTRUCTION MATERIAL', '1'),
(NULL, 'lg_construction_material', 'MATERIEL DE CONSTRUCTION', '2'),
(NULL, 'lg_fresh_products', 'FRESH PRODUCTS', '1'),
(NULL, 'lg_fresh_products', 'PRODUITS FRAIS', '2'),
(NULL, 'lg_hazardous_products', 'HAZARDOUS PRODUCTS', '1'),
(NULL, 'lg_hazardous_products', 'PRODUITS DANGEUREUX', '2'),
(NULL, 'lg_hardware_products', 'HARDWARE PRODUCTS', '1'),
(NULL, 'lg_hardware_products', 'PRODUITS QUICAILLERIE', '2'),
(NULL, 'lg_appliances', 'APPLIANCES', '1'),
(NULL, 'lg_appliances', 'ELECTROMENAGERS', '2'),
(NULL, 'lg_fragile_lamp_glasses', 'FRAGILE - LAMPS - GLASSES', '1'),
(NULL, 'lg_fragile_lamp_glasses', 'FRAGILES - LAMPES - VERRES', '2'),
(NULL, 'lg_variety', 'VARIETY', '1'),
(NULL, 'lg_variety', 'DIVERS', '2'),
(NULL, 'lg_menu', 'Menu', '1'),
(NULL, 'lg_menu', 'Menu', '2'),
(NULL, 'lg_user_count_text', 'B2B users', '1'),
(NULL, 'lg_user_count_text', 'Utilisateurs B2B', '2'),
(NULL, 'lg_see_all_vehicles', 'see all vehicles', '1'),
(NULL, 'lg_see_all_vehicles', 'Voir tous les véhicules', '2'),
(NULL, 'lg_recent_reviews', 'Recent reviews', '1'),
(NULL, 'lg_recent_reviews', 'Critiques récentes', '2'),
(NULL, 'lg_high_companies', 'Recently reviewed companies', '1'),
(NULL, 'lg_high_companies', 'Sociétés récemment critiquées', '2'),
(NULL, 'lg_office_address', 'Office address', '1'),
(NULL, 'lg_office_address', 'Adresse de bureau', '2'),
(NULL, 'lg_office_address_text', 'PEP. entreprise 3 technopole Sfax 3021. Tunisie', '1'),
(NULL, 'lg_office_address_text', 'PEP. entreprise 3 technopole Sfax 3021. Tunisie', '2'),
(NULL, 'lg_office_address_phone', '+216 28716 111', '1'),
(NULL, 'lg_office_address_phone', '+216 28716 111', '2'),
(NULL, 'lg_useful_links', 'Useful links', '1'),
(NULL, 'lg_useful_links', 'Liens utiles', '2'),
(NULL, 'lg_about_us', 'About us', '1'),
(NULL, 'lg_about_us', 'À propos de nous', '2'),
(NULL, 'lg_blog', 'Blog', '1'),
(NULL, 'lg_blog', 'Blog', '2'),
(NULL, 'lg_help_support', 'Help & Support', '1'),
(NULL, 'lg_help_support', 'Assistance', '2'),
(NULL, 'lg_FAQ', 'FAQ', '1'),
(NULL, 'lg_FAQ', 'FAQ', '2'),
(NULL, 'lg_contact_us', 'Contact us', '1'),
(NULL, 'lg_contact_us', 'Nous contacter', '2'),
(NULL, 'lg_privacy_policy', 'Privacy policy', '1'),
(NULL, 'lg_privacy_policy', 'Nous contacter', '2'),
(NULL, 'lg_term_condition', 'Terms and conditions', '1'),
(NULL, 'lg_term_condition', ' Termes et conditions', '2'),
(NULL, 'lg_mobile_application', 'Mobile application', '1'),
(NULL, 'lg_mobile_application', 'Application mobile', '2'),
(NULL, 'lg_download_our_app', 'Download our App', '1'),
(NULL, 'lg_download_our_app', 'Téléchargez notre application', '2'),
(NULL, 'lg_keyword', 'Keyword', '1'),
(NULL, 'lg_keyword', 'mot-clé', '2'),
(NULL, 'lg_filters', 'FILTERS', '1'),
(NULL, 'lg_filters', 'FILTRES', '2'),
(NULL, 'lg_clear_all', 'Clear All', '1'),
(NULL, 'lg_clear_all', 'Effacer Touts', '2'),
(NULL, 'lg_results', 'Results', '1'),
(NULL, 'lg_results', 'Résultats', '2'),
(NULL, 'lg_max_count', 'Max number', '1'),
(NULL, 'lg_max_count', 'Nombre maximum', '2'),
(NULL, 'lg_invoices', 'Invoices', '1'),
(NULL, 'lg_invoices', 'Factures', '2'),
(NULL, 'lg_profile', 'Profile', '1'),
(NULL, 'lg_profile', 'Profile', '2'),
(NULL, 'lg_confirm_payment', 'Confirm payment', '1'),
(NULL, 'lg_confirm_payment', 'Confirmer le paiement', '2'),
(NULL, 'lg_mark_request_as_paid', 'Mark this request as paid', '1'),
(NULL, 'lg_mark_request_as_paid', 'Marquer cette demande comme payée', '2'),
(NULL, 'lg_paid', 'paid', '1'),
(NULL, 'lg_paid', 'payé', '2'),
(NULL, 'lg_not_paid', 'not paid', '1'),
(NULL, 'lg_not_paid', 'non payé', '2'),
(NULL, 'lg_invoicing', 'Invoicing', '1'),
(NULL, 'lg_invoicing', 'Facturation', '2'),
(NULL, 'lg_missing_company_infos', 'please fill in the missing information below in your company profile before proceeding', '1'),
(NULL, 'lg_missing_company_infos', "veuillez compléter les informations manquantes ci-dessous dans votre profil d'entreprise avant de continuer", '2'),
(NULL, 'lg_unit', 'Unit', '1'),
(NULL, 'lg_unit', 'Unitaire', '2'),
(NULL, 'lg_quantity', 'Quantity', '1'),
(NULL, 'lg_quantity', 'Quantité', '2'),
(NULL, 'lg_invoicing_date', 'Invoicing date', '1'),
(NULL, 'lg_invoicing_date', 'Date de facturation', '2'),
(NULL, 'lg_invoice_number', 'Invoice №', '1'),
(NULL, 'lg_invoice_number', 'Facture №', '2'),
(NULL, 'lg_tax_stamp', 'Tax stamp', '1'),
(NULL, 'lg_tax_stamp', 'Timbre fiscal', '2'),
(NULL, 'lg_VAT', 'VAT', '1'),
(NULL, 'lg_VAT', 'TVA', '2'),
(NULL, 'lg_generate_invoices', 'Generate invoices', '1'),
(NULL, 'lg_generate_invoices', 'Générer des factures', '2'),
(NULL, 'lg_unavailable_invoices', "Invoice unavailable", '1'),
(NULL, 'lg_unavailable_invoices', 'Facture non disponible', '2'),
(NULL, 'lg_available_invoices', "Invoice available", '1'),
(NULL, 'lg_available_invoices', 'Facture disponible', '2'),
(NULL, 'lg_info_save_succ', "information saved successfully", '1'),
(NULL, 'lg_info_save_succ', 'informations enregistrées avec succès', '2'),
(NULL, 'lg_user_add_succ', "user added successfully", '1'),
(NULL, 'lg_user_add_succ', 'utilisateur ajouté avec succès', '2'),
(NULL, 'lg_vehicle_add_succ', "vehicle added successfully", '1'),
(NULL, 'lg_vehicle_add_succ', 'véhicule ajouté avec succès', '2'),
(NULL, 'lg_user_delete_succ', "user deleted successfully", '1'),
(NULL, 'lg_user_delete_succ', 'utilisateur supprimé avec succès', '2'),
(NULL, 'lg_vehicle_delete_succ', "vehicle deleted successfully", '1'),
(NULL, 'lg_vehicle_delete_succ', 'véhicule supprimé avec succès', '2'),
(NULL, 'lg_attri_add_succ', "attribution added successfully", '1'),
(NULL, 'lg_attri_add_succ', 'attribution ajoutée avec succès', '2'),
(NULL, 'lg_attri_delete_succ', "attribution deleted successfully", '1'),
(NULL, 'lg_attri_delete_succ', 'attribution supprimée avec succès', '2'),
(NULL, 'lg_invoice_gen_succ', "invoices generated successfully", '1'),
(NULL, 'lg_invoice_gen_succ', 'factures générées avec succès', '2'),
(NULL, 'lg_job_completed_succ', "job completed successfully", '1'),
(NULL, 'lg_job_completed_succ', 'travail terminé avec succès', '2'),
(NULL, 'lg_request_completed_succ', "request completed successfully", '1'),
(NULL, 'lg_request_completed_succ', 'demande terminé avec succès', '2'),
(NULL, 'lg_offer_post_succ', "proposition sent successfully", '1'),
(NULL, 'lg_offer_post_succ', 'proposition envoyée avec succès', '2'),
(NULL, 'lg_offer_edit_succ', "proposition modified successfully", '1'),
(NULL, 'lg_offer_edit_succ', 'proposition modifiée avec succès', '2'),
(NULL, 'lg_offer_delete_succ', "proposition deleted successfully", '1'),
(NULL, 'lg_offer_delete_succ', 'proposition supprimée avec succès', '2'),
(NULL, 'lg_offer_already_accepted', "proposition is already accecpted", '1'),
(NULL, 'lg_offer_already_accepted', 'proposition déjà acceptée', '2'),
(NULL, 'lg_offer_accepted_succ', "proposition accecpted successfully", '1'),
(NULL, 'lg_offer_accepted_succ', 'proposition acceptée avec succès', '2'),
(NULL, 'lg_offer_is_deleted', "proposition is deleted", '1'),
(NULL, 'lg_offer_is_deleted', 'proposition est supprimée', '2'),
(NULL, 'lg_request_init_succ', "request initiated successfully", '1'),
(NULL, 'lg_request_init_succ', 'demande lancée avec succès', '2'),
(NULL, 'lg_request_validated_succ', "request validated successfully", '1'),
(NULL, 'lg_request_validated_succ', 'demande validée avec succès', '2'),
(NULL, 'lg_request_deleted_succ', "request deleted successfully", '1'),
(NULL, 'lg_request_deleted_succ', 'demande supprimée avec succès', '2'),
(NULL, 'lg_request_reported_succ', "report sent successfully", '1'),
(NULL, 'lg_request_reported_succ', 'rapport envoyé avec succès', '2'),
(NULL, 'lg_connection_errror_msg_title', "an error has occured", '1'),
(NULL, 'lg_connection_errror_msg_title', 'une erreur a eu lieu', '2'),
(NULL, 'lg_connection_errror_msg', "please make sure your connection is stable then try again", '1'),
(NULL, 'lg_connection_errror_msg', 'Assurez-vous que votre connexion est stable, puis réessayez', '2'),
(NULL, 'lg_address_add_succ', "address added successfully", '1'),
(NULL, 'lg_address_add_succ', 'adresse ajoutée avec succès', '2'),
(NULL, 'lg_address_delete_succ', "address deleted successfully", '1'),
(NULL, 'lg_address_delete_succ', 'adresse supprimée avec succès', '2'),
(NULL, 'lg_merch_form_notice', "Notice: all fields are mandatory except the ones in 'options'", '1'),
(NULL, 'lg_merch_form_notice', "Remarque : tous les champs sont obligatoires sauf ceux dans 'options'", '2'),
(NULL, 'lg_est_distance', "Estimated distance", '1'),
(NULL, 'lg_est_distance', "Distance estimée", '2'),
(NULL, 'lg_est_duration', "Estimated duration", '1'),
(NULL, 'lg_est_duration', "Durée estimée", '2'),
(NULL, 'lg_enter_budget', "Enter your budget", '1'),
(NULL, 'lg_enter_budget', "Enter votre budget", '2'),
(NULL, 'lg_enter_number', "Enter the number", '1'),
(NULL, 'lg_enter_number', "Enter le nombre", '2');


INSERT INTO `admin_interface_theme` (`id`, `name`, `active`, `title`, `title_visible`, `logo`, `logo_visible`, `css_header_background_color`, `title_color`, `css_header_text_color`, `css_header_link_color`, `css_header_link_hover_color`, `css_module_background_color`, `css_module_text_color`, `css_module_link_color`, `css_module_link_hover_color`, `css_module_rounded_corners`, `css_generic_link_color`, `css_generic_link_hover_color`, `css_save_button_background_color`, `css_save_button_background_hover_color`, `css_save_button_text_color`, `css_delete_button_background_color`, `css_delete_button_background_hover_color`, `css_delete_button_text_color`, `list_filter_dropdown`, `related_modal_active`, `related_modal_background_color`, `related_modal_rounded_corners`, `logo_color`, `recent_actions_visible`, `favicon`, `related_modal_background_opacity`, `env_name`, `env_visible_in_header`, `env_color`, `env_visible_in_favicon`, `related_modal_close_button_visible`, `language_chooser_active`, `language_chooser_display`, `list_filter_sticky`, `form_pagination_sticky`, `form_submit_sticky`, `css_module_background_selected_color`, `css_module_link_selected_color`, `logo_max_height`, `logo_max_width`, `foldable_apps`, `language_chooser_control`, `list_filter_highlight`, `list_filter_removal_links`, `show_fieldsets_as_tabs`, `show_inlines_as_tabs`, `css_generic_link_active_color`) VALUES
(1, 'Optima', 1, 'Optima administration', 1, 'defaults/logos/H_logo.png', 1, '#FFFFFF', '#FF5B37', '#FF5B37', '#FF836C', '#FF5B37', '#FF5B37', '#FFFFFF', '#FFFFFF', '#FF5B37', 1, '#FF5B37', '#FF5B37', '#FF5B37', '#E55231', '#FFFFFF', '#FF5B37', '#E55231', '#FFFFFF', 1, 1, '#000000', 1, '#FFFFFF', 1, 'defaults/logos/logo.png', '0.3', 'Optima', 1, '#FF5B37', 1, 1, 1, 'code', 1, 1, 1, '#FFF1F1', '#FFFFFF', 60, 400, 1, 'default-select', 1, 0, 0, 0, '#FF5B37');